### ISSUE TITLE
Hi, I need a relationship advice...

### ISSUE THREAD

**Issue by OPENCUP** [HardGameSs/PSX#30]
Hi, my name is James, I am 17 and a college student, I am a beginner Twitch streamer, I study software engineering from home. Today I will tell you about my room setup, here you can see that i really like Nintendo games, by posters I have and I have a really aesthetic room, as you can see it's all white and comfy, here you can see my table, it's made out of white wood and my mid-range RTX 3070Ti pc with I7 12500k and 32 gigs of ram for software engineering and coding, i have 2 monitors, one is 1440p Acer and second is vertical, same monitor, my desktop wallpapers are really simple and clean, I use Rainmeter to add widgets, I own a PS5 and 3 Nintendo switches, with 4 controllers, for my peripherals: I got G305 logitech mouse, Razer keyboard and black mousepad on my table. Speaking of peripherals, I have an iPhone 13 Pro Max 256gb, iPad Pro and Apple pencil for drawing. While making this video i used Final Cut Pro on my MacBook Pro M1, thank you for reading my self bio, bye!

**Comment by stavratum** [comment]
im female
